# SPDX-FileCopyrightText: 2025 Humanoid Sensing and Perception, Istituto Italiano di Tecnologia
# SPDX-License-Identifier: BSD-3-Clause

name: fsosar
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - transformers
  - scikit-learn
  - wandb
  - matplotlib
  - opencv
  - einops
  - pip
  - pip:
    - git+https://github.com/openai/CLIP.git
    - imageio